### ISSUE TITLE
Error in

### ISSUE THREAD

**Issue by lvzimi** [YuanmingZhang65/FastBiCmrMLM#4]

**Comment by YuanmingZhang65** [comment]
请将数据发给我，以便检查问题的由来



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 8, 2024 21:15 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [YuanmingZhang65/FastBiCmrMLM] Error in { :    task 1 failed - "errorin evaluating the argument 'x' in selecting a method for function 'ncol':object 'snp_index_df2' not found" (Issue #4)




 
老师您好，我运行示例的数据的时候没有问题，但运行自己的数据会报错：
 我的数据是由012编码的CSV文件改为ped与map后，再用plink转为bed，fam，bim文件后进行运算的，出现了如下报错，不知道哪里出了问题，希望得到老师的帮助：
 (FastBiCmrMLM) ***@***.*** test]$ Rscript test.R
 Extracting number of samples and rownames from 11089.fam...
 Extracting number of variants and colnames from 11089.bim...
 [1] "prepare-GRM time:"
 Time difference of 7.342918 secs
 [1] "Analysizing the trait: 1"
 [1] "tau time:"
 Time difference of 5.249787 secs
 Error in { :
 task 1 failed - "error in evaluating the argument 'x' in selecting a method for function 'ncol': object 'snp_index_df2' not found"
 Calls: FastBiCmrMLM -&gt; GmrMLM_single_env023 -&gt; %dopar% -&gt; 
 Execution halted

**Comment by lvzimi** [comment]
麻烦老师了，原始012编码的csv文件和我根据原始文件创建的ped、map文件都在该压缩包中。




liangzirui1229
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuanmingZhang65/FastBiCmrMLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月8日(星期一) 晚上11:44
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [YuanmingZhang65/FastBiCmrMLM] Error in (Issue #4)





 请将数据发给我，以便检查问题的由来 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Mon, Jul 8, 2024 21:15 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;; 
 Subject: [YuanmingZhang65/FastBiCmrMLM] Error in { :    task 1 failed - "errorin evaluating the argument 'x' in selecting a method for function 'ncol':object 'snp_index_df2' not found" (Issue #4) 
 
 
 
 
   
 老师您好，我运行示例的数据的时候没有问题，但运行自己的数据会报错： 
  我的数据是由012编码的CSV文件改为ped与map后，再用plink转为bed，fam，bim文件后进行运算的，出现了如下报错，不知道哪里出了问题，希望得到老师的帮助： 
  (FastBiCmrMLM) ***@***.*** test]$ Rscript test.R 
  Extracting number of samples and rownames from 11089.fam... 
  Extracting number of variants and colnames from 11089.bim... 
  [1] "prepare-GRM time:" 
  Time difference of 7.342918 secs 
  [1] "Analysizing the trait: 1" 
  [1] "tau time:" 
  Time difference of 5.249787 secs 
  Error in { : 
  task 1 failed - "error in evaluating the argument 'x' in selecting a method for function 'ncol': object 'snp_index_df2' not found" 
  Calls: FastBiCmrMLM -&amp;gt; GmrMLM_single_env023 -&amp;gt; %dopar% -&amp;gt;  
  Execution halted 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

11089.zip (8.67M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f343432d5644dcf640d4cae16330a1f4940040252070c041c075507561e0d5150571950510b0b1d0606525052055e0901010707303a380100040c0b1e4951403109&t=exs_ftn_download&code=14420380

**Comment by YuanmingZhang65** [comment]
***@***.***, 他来检查你的问题



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 9, 2024 00:24 AM
To: ***@***.***&gt;;
Cc: "Yuan-Ming ***@***.******@***.***&gt;;
Subject: Re: [YuanmingZhang65/FastBiCmrMLM] Error in (Issue #4)




 麻烦老师了，原始012编码的csv文件和我根据原始文件创建的ped、map文件都在该压缩包中。 
 
 
 
 
 liangzirui1229 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "YuanmingZhang65/FastBiCmrMLM"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年7月8日(星期一) 晚上11:44 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [YuanmingZhang65/FastBiCmrMLM] Error in (Issue #4) 
 
 
 
 
 
  请将数据发给我，以便检查问题的由来  
   
   
   
  ---Original---  
  From: ***@***.***&amp;amp;gt;  
  Date: Mon, Jul 8, 2024 21:15 PM  
  To: ***@***.***&amp;amp;gt;;  
  Cc: ***@***.***&amp;amp;gt;;  
  Subject: [YuanmingZhang65/FastBiCmrMLM] Error in { :    task 1 failed - "errorin evaluating the argument 'x' in selecting a method for function 'ncol':object 'snp_index_df2' not found" (Issue #4)  
   
   
   
   
     
  老师您好，我运行示例的数据的时候没有问题，但运行自己的数据会报错：  
   我的数据是由012编码的CSV文件改为ped与map后，再用plink转为bed，fam，bim文件后进行运算的，出现了如下报错，不知道哪里出了问题，希望得到老师的帮助：  
   (FastBiCmrMLM) ***@***.*** test]$ Rscript test.R  
   Extracting number of samples and rownames from 11089.fam...  
   Extracting number of variants and colnames from 11089.bim...  
   [1] "prepare-GRM time:"  
   Time difference of 7.342918 secs  
   [1] "Analysizing the trait: 1"  
   [1] "tau time:"  
   Time difference of 5.249787 secs  
   Error in { :  
   task 1 failed - "error in evaluating the argument 'x' in selecting a method for function 'ncol': object 'snp_index_df2' not found"  
   Calls: FastBiCmrMLM -&amp;amp;gt; GmrMLM_single_env023 -&amp;amp;gt; %dopar% -&amp;amp;gt;   
   Execution halted  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;gt; 
 
 
 从QQ邮箱发来的超大附件 
 
 11089.zip (8.67M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f343432d5644dcf640d4cae16330a1f4940040252070c041c075507561e0d5150571950510b0b1d0606525052055e0901010707303a380100040c0b1e4951403109&amp;t=exs_ftn_download&amp;code=14420380

**Comment by lvzimi** [comment]
老师您好！
&nbsp; &nbsp; &nbsp; 我的问题已解决，我的参数设置错误，"FastBiCmrMLM",应为"FastBiCmrMLM-Time"，且012编码未转为单碱基ATCG格式，修复这些错误后程序可以正常使用。
&nbsp; &nbsp; &nbsp; 感谢您的回复！
&nbsp; &nbsp; &nbsp;&nbsp;


liangzirui1229
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuanmingZhang65/FastBiCmrMLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 上午10:22
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [YuanmingZhang65/FastBiCmrMLM] Error in (Issue #4)





 ***@***.***, 他来检查你的问题 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Tue, Jul 9, 2024 00:24 AM 
 To: ***@***.***&amp;gt;; 
 Cc: "Yuan-Ming ***@***.******@***.***&amp;gt;; 
 Subject: Re: [YuanmingZhang65/FastBiCmrMLM] Error in (Issue #4) 
 
 
 
 
  麻烦老师了，原始012编码的csv文件和我根据原始文件创建的ped、map文件都在该压缩包中。  
   
   
   
   
  liangzirui1229  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "YuanmingZhang65/FastBiCmrMLM"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2024年7月8日(星期一) 晚上11:44  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [YuanmingZhang65/FastBiCmrMLM] Error in (Issue #4)  
   
   
   
   
   
   请将数据发给我，以便检查问题的由来   
     
     
     
   ---Original---   
   From: ***@***.***&amp;amp;amp;gt;   
   Date: Mon, Jul 8, 2024 21:15 PM   
   To: ***@***.***&amp;amp;amp;gt;;   
   Cc: ***@***.***&amp;amp;amp;gt;;   
   Subject: [YuanmingZhang65/FastBiCmrMLM] Error in { :    task 1 failed - "errorin evaluating the argument 'x' in selecting a method for function 'ncol':object 'snp_index_df2' not found" (Issue #4)   
     
     
     
     
       
   老师您好，我运行示例的数据的时候没有问题，但运行自己的数据会报错：   
    我的数据是由012编码的CSV文件改为ped与map后，再用plink转为bed，fam，bim文件后进行运算的，出现了如下报错，不知道哪里出了问题，希望得到老师的帮助：   
    (FastBiCmrMLM) ***@***.*** test]$ Rscript test.R   
    Extracting number of samples and rownames from 11089.fam...   
    Extracting number of variants and colnames from 11089.bim...   
    [1] "prepare-GRM time:"   
    Time difference of 7.342918 secs   
    [1] "Analysizing the trait: 1"   
    [1] "tau time:"   
    Time difference of 5.249787 secs   
    Error in { :   
    task 1 failed - "error in evaluating the argument 'x' in selecting a method for function 'ncol': object 'snp_index_df2' not found"   
    Calls: FastBiCmrMLM -&amp;amp;amp;gt; GmrMLM_single_env023 -&amp;amp;amp;gt; %dopar% -&amp;amp;amp;gt;    
    Execution halted   
       
   —   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;amp;amp;gt;   
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;amp;gt;  
   
   
  从QQ邮箱发来的超大附件  
   
  11089.zip (8.67M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f343432d5644dcf640d4cae16330a1f4940040252070c041c075507561e0d5150571950510b0b1d0606525052055e0901010707303a380100040c0b1e4951403109&amp;amp;t=exs_ftn_download&amp;amp;code=14420380
